name: antares
channels:
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - libedit
  - libffi
  - libgcc-ng
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip=10.0.1
  - python=3.7.1
  - readline
  - scikit-learn
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
